<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>THE BEST</title>
</head>
<body>
    <#import "/macros/nav.ftlh" as ui>
    <#import "/macros/title.ftlh" as title>
    <@ui.nav></@ui.nav>
    <@title.title title="The best is .NET"></@title.title>

</body>
</html>