# Création app
FROM node:24-alpine AS builder
 
WORKDIR /app

COPY package*.json .

RUN npm i

COPY . . 

RUN npm run build

# Création serveur nginx
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80