<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About</title>
</head>
<body>
    <#import "/macros/nav.ftlh" as nav>
    <#import "/macros/title.ftlh" as title>
    <@nav.nav></@nav.nav>
    <@title.title title="About"></@title.title>
</body>
</html>