CREATE TABLE product (
id INT UNIQUE NOT NULL,
ref_mag VARCHAR(50),
ref_fab VARCHAR(50),
EAN13 INT,
price NUMERIC(12, 2),
CONSTRAINT fk_tva FOREIGN KEY(tva_id)
	REFERENCES T_TAUX_TVA(id)
CONSTRAINT fk_tva FOREIGN KEY(ryn_id)
	REFERENCES T_RAYON_RYN(id)
CONSTRAINT fk_tva FOREIGN KEY(fab_id)
	REFERENCES T_FABRICANT_FBQ(id)

);