-- 1

ALTER TABLE Section
ALTER COLUMN delegate_id DROP NOT NULL;


-- 2

ALTER TABLE Section
ADD CONSTRAINT fk_section_delegate
FOREIGN KEY (delegate_id)
REFERENCES Student(student_id);


-- 3

ALTER TABLE Student DROP COLUMN course_id;

-- 4 

ALTER TABLE Student
ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY; 

-- 5

ALTER TABLE Professor DROP CONSTRAINT FK_professor_section;
ALTER TABLE Student DROP CONSTRAINT FK_student_section;

ALTER TABLE Section
ALTER COLUMN section_id TYPE CHAR(4)
USING TO_CHAR(section_id, 'FM0000');

ALTER TABLE Professor
ALTER COLUMN section_id TYPE CHAR(4)
USING TO_CHAR(section_id, 'FM0000');
ALTER TABLE Student
ALTER COLUMN section_id TYPE CHAR(4)
USING TO_CHAR(section_id, 'FM0000');

ALTER TABLE Professor
ADD CONSTRAINT FK_professor_section
FOREIGN KEY (section_id)
REFERENCES Section(section_id);
ALTER TABLE Student
ADD CONSTRAINT FK_student_section
FOREIGN KEY (section_id)
REFERENCES Section(section_id);


