spring:
  application:
    name: firstApiRest

  datasource:
    url: jdbc:postgresql://localhost:5432/my_shop
    username: postgres
    password: Hugo099!
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true